apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dcv-checker
    version: v1
  name: dcv-checker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dcv-checker
      version: v1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dcv-checker
        version: v1
    spec:
      containers:
        - image: ghcr.io/open-mpic/dcv_checker:latest
          name: dcv-checker
          ports:
            - containerPort: 80
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: app-conf
              mountPath: /app/config/app.conf
              subPath: app.conf
      restartPolicy: Always
      volumes:
        - name: app-conf
          configMap:
            name: dcv-config
