apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deploy.yaml
  - service.yaml

configMapGenerator:
  - name: dcv-config
    files: # using files here as we want to create a whole file
      - files/app.conf
