available_regions:
  -
    code: "example-region-1"
    name: "Africa (Cape Town)"
    rir: "arin"
    too_close_codes: []
  -
    code: "example-region-2"
    name: "Asia Pacific (Hong Kong)"
    rir: "apnic"
    too_close_codes: []